version: "3.7"

# Service Definitions
services:

  app:
    build:
      context: .
      dockerfile: ./build/myapp/Dockerfile
    environment:
      NODE_ENV: "development" # auto-reloads app on save
      CACHE_VIEWS: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./app/myapp:/app

secrets:
  adonis.appkey:
    external: false
    file: ./docker-secrets/adonis.appkey.v1